In [82]:
import numpy as np

In [83]:
# Create a 3x5 array filled with Pi ~3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [84]:
# Array filled w/linear sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [85]:
# Create array of five values evenly space
np.linspace(0, 1, 5) # Good use for quantiles 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [86]:
# random values
np.random.random((3,3))

array([[0.45674792, 0.26828131, 0.8370528 ],
       [0.27051466, 0.53006201, 0.17537266],
       [0.31496645, 0.8911091 , 0.18033628]])

In [87]:
# 3 x 3 array of normally distributed random values : mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.48630088, -0.02936315, -1.23714237],
       [ 0.07598604, -1.94519772, -0.23484041],
       [-1.81456729,  0.05963647, -0.39763149]])

In [88]:
# 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Set DType with Numpy Arrays (Numpy Standard Types of Note)
* bool_ 
* int_ : Default integer type (normally either int64 or int32)
* intc : Identical to C (int32 || int64) generally
* int8 : Byte (-128 to 127)
* int16: Integer(-32768 to 32767)
* int32 : Integer (-2,147,483,648 to 2,147,483,648)
* uint8 : Unsigned integer (0 to 255)
* uint16 : Unsigned integer (0 to 65535)
* uint32 : Unsigned Integer (0 to 4294967295)

You get the picture

In [89]:
np.random.seed(123) # seed for reproducibility
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4, 5))
print(x1, '\n\n', x2, '\n\n', x3, '\n')
print("x3 ndim: ", x3.ndim)
print("x3shape: ", x3.shape)
print("x3size: ", x3.size)

[2 2 6 1 3 9] 

 [[6 1 0 1]
 [9 0 0 9]
 [3 4 0 0]] 

 [[[4 1 7 3 2]
  [4 7 2 4 8]
  [0 7 9 3 4]
  [6 1 5 6 2]]

 [[1 8 3 5 0]
  [2 6 2 4 4]
  [6 3 0 6 4]
  [7 6 7 1 5]]

 [[7 9 2 4 8]
  [1 2 1 1 3]
  [5 9 0 8 1]
  [6 3 3 5 9]]] 

x3 ndim:  3
x3shape:  (3, 4, 5)
x3size:  60


In [90]:
print(x2)
print('\n')
x2[0, 0] = 12 # change first column in first row
x2[1, 0] = x2[1, 0] + 5 # reassign existing value to new value with existing value included
x2

[[6 1 0 1]
 [9 0 0 9]
 [3 4 0 0]]




array([[12,  1,  0,  1],
       [14,  0,  0,  9],
       [ 3,  4,  0,  0]])

In [91]:
# Acccess Three Dimension
x3[1, 2, :] # Second Set, Third Row, All Values 

array([6, 3, 0, 6, 4])

In [92]:
print(x1)
x1[1::2] # step to use select elements by slicing and using the step parameter for indexing

[2 2 6 1 3 9]


array([2, 1, 9])

In [93]:
# can reverse too
x1[-1::-2]

array([9, 1, 2])

In [94]:
print(x2)
# Multidimensional subarrays
x2[:2, :3] # two rows, three columns

[[12  1  0  1]
 [14  0  0  9]
 [ 3  4  0  0]]


array([[12,  1,  0],
       [14,  0,  0]])

In [95]:
x2[:, ::2] # all rows, every other column

array([[12,  0],
       [14,  0],
       [ 3,  0]])

In [96]:
x2[::-1, ::-1] # reversed all together

array([[ 0,  0,  4,  3],
       [ 9,  0,  0, 14],
       [ 1,  0,  1, 12]])

In [97]:
# Subarrays as no-copy views
x2_sub = x2[:2, :2]
x2_sub

array([[12,  1],
       [14,  0]])

In [98]:
x2_sub[0, :] = 24
x2_sub

array([[24, 24],
       [14,  0]])

In [99]:
x2 # original array subbed section is also updated in the parent array we created a sub array from

array([[24, 24,  0,  1],
       [14,  0,  0,  9],
       [ 3,  4,  0,  0]])

* Creating a copy of the array won't influence the parent should the child be updated
```python
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
[[24 24]
[14  0]]
```
```python
x2_sub_copy[0, :] = 48
print(x2_sub_copy)
[[48 48]
[14  0]]
```
```python
print(x2)
[[24 24  0  1]
[14  0  0  9]
[ 3  4  0  0]]
```
* After modifying our subset we can see that the original array is not altered from the copied subset updates

In [100]:
# Reshape Arrays
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [102]:
x.reshape((1,3)) # row vector via reshape

array([[1, 2, 3]])

In [103]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

### Array Concatenation & Splitting

In [104]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [105]:
grid = np.concatenate([x, y]).reshape((2,3))
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
## concatenate two-dimensional arrays
print(np.concatenate([grid, grid]))
print('\n', 'Flipped Second Grid : Row order and Element Order flipped for use of second grid')
print(np.concatenate([grid, np.flip(grid)]))
print('\n', 'Array rows flipped in order but element order in list maintained')
print(np.concatenate([grid, grid[::-1]]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

 Flipped Second Grid : Row order and Element Order flipped for use of second grid
[[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]]

 Array rows flipped in order but element order in list maintained
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [1 2 3]]


In [107]:
# concatenate along the second axis (zero-indexed) (joins same indexed rows together into single row)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [108]:
# Vertical and Horizontal Stack (More Likely you'll be using the Vertical Stack)
grid_2 = np.array([[9,8,7], [6,5,4]])
print(np.vstack([x, grid_2]))
print('\n') # Horizontal stack a bit trickier as the total rows in each numpy array would need to match unlike a vertical stack looking at columns
print(np.hstack([grid_2, [[24], [8]]]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]


[[ 9  8  7 24]
 [ 6  5  4  8]]


In [109]:
## Splitting of arrays
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3, 5]) # split the passed list at indexes 3 = 99, and 5 = 3 (two splits needed for three value unpacking into tuples)
print(x1, x2, x3) # N split points lead to N + 1 subarrays

[1 2 3] [99 99] [3 2 1]


In [110]:
grid = np.arange(1, 17).reshape(4, 4)
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [111]:
# vertical split
upper, lower = np.vsplit(grid, [2])
print(upper)
print('\n')
print(lower)

[[1 2 3 4]
 [5 6 7 8]]


[[ 9 10 11 12]
 [13 14 15 16]]


In [112]:
# horizontal split
left, right = np.hsplit(grid, [2])
print(left)
print('\n')
print(right)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
